### ISSUE TITLE
$email

### ISSUE THREAD

**Issue by michaelrain** [dideex/coffeein#1]
https://github.com/dideex/coffeein/blob/845966c9d6afa8cdaba49345aaf930b0e30b2252/app/js/scripts.js#L342

variable email, calls like '$email' in ajax data. Is a correct?

**Comment by dideex** [comment]
yep, it works fine, but acctualy can use es6 standartslike 
let $email ....
....
data: {phone: $input.val(), $email}

**Comment by michaelrain** [comment]
Interesting, Thank You!
